services:
  - type: web
    name: telegram-bot
    env: python
    repo: https://github.com/abdullohpx-byte/my-telegram-bot.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    autoDeploy: true
    # Cron job to restart the bot at 05:01 UTC daily
    cron:
      - schedule: "1 5 * * *"
        command: "python bot.py"
